package com.ns
/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'apimentel' at '9/6/16 12:05 PM' with Gradle 2.7
 *
 * @author apimentel, @date 9/6/16 12:05 PM
 */


import spock.lang.Specification

class LibraryTest extends Specification{
    def "hello returns correct message"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.helloWorld("Angel")
        then:
        result == "Hello Angel"
    }
}
