package com.ns
/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'apimentel' at '9/6/16 12:05 PM' with Gradle 2.7
 *
 * @author apimentel, @date 9/6/16 12:05 PM
 */
class Library {
    private static String hello = "Hello "
    String helloWorld(String name) {
        hello+name;
    }
}
